packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - nx
  - sharp
ignoredBuiltDependencies:
  - esbuild
allowBuilds:
  '@scarf/scarf': set this to true or false
  esbuild: false
  nx: true
  sharp: true
