packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - nx
  - sharp
ignoredBuiltDependencies:
  - esbuild
allowBuilds:
  '@parcel/watcher': false
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: false
  nx: true
  sharp: true
