import "reflect-metadata";
import path from "node:path";
import {
  AccessAuditLog,
  Conversation,
  ConversationMessage,
  ConversationParticipant,
  CustomSmtp,
  Department,
  DepartmentDispatchRelation,
  EmailLog,
  EmailTemplate,
  EmailVerification,
  IntegrationToken,
  Invite,
  NotificationDestination,
  Organization,
  OrganizationContact,
  OrganizationGroup,
  OrganizationGroupMember,
  OrganizationLanguage,
  OrganizationSetting,
  PasswordReset,
  Permission,
  PlatformEmailTemplate,
  PlatformRole,
  PlatformRolePermission,
  PlatformSetting,
  PlatformSmtp,
  PlatformUser,
  PlatformUserRole,
  Role,
  RolePermission,
  Ticket,
  TicketMessage,
  Tenant,
  TenantApplication,
  TenantSetting,
  User,
  UserDepartment,
  UserDepartmentRole,
  UserNotification,
  UserOrganization,
  UserOrganizationRole,
  UserTenantRole,
} from "@hermes-swarm/core";
import { DataSource } from "typeorm";
import { databaseRuntimeConfig } from "../config/runtime-config.js";

const database = databaseRuntimeConfig();

/** Release-only datasource. API instances never auto-apply migrations. */
export default new DataSource({
  type: "postgres",
  url: database.url,
  entities: [
    AccessAuditLog,
    Conversation,
    ConversationMessage,
    ConversationParticipant,
    CustomSmtp,
    Department,
    DepartmentDispatchRelation,
    EmailLog,
    EmailTemplate,
    EmailVerification,
    IntegrationToken,
    Invite,
    NotificationDestination,
    Organization,
    OrganizationContact,
    OrganizationGroup,
    OrganizationGroupMember,
    OrganizationLanguage,
    OrganizationSetting,
    PasswordReset,
    Permission,
    PlatformEmailTemplate,
    PlatformRole,
    PlatformRolePermission,
    PlatformSetting,
    PlatformSmtp,
    PlatformUser,
    PlatformUserRole,
    Role,
    RolePermission,
    Ticket,
    TicketMessage,
    Tenant,
    TenantApplication,
    TenantSetting,
    User,
    UserDepartment,
    UserDepartmentRole,
    UserNotification,
    UserOrganization,
    UserOrganizationRole,
    UserTenantRole,
  ],
  migrations: [path.join(import.meta.dirname, "migrations", "*.{js,ts}")],
  synchronize: false,
});
