import { z } from "zod";

/** Stable public error codes for the analytics boundary. */
export const ANALYTICS_ERROR_CODES = [
  "ANALYTICS_FEATURE_DISABLED",
  "ANALYTICS_CONTEXT_REQUIRED",
  "ANALYTICS_SOURCE_NOT_FOUND",
  "ANALYTICS_SOURCE_FORBIDDEN",
  "ANALYTICS_SOURCE_REVISION_MISMATCH",
  "ANALYTICS_CONTRACT_VERSION_UNSUPPORTED",
  "ANALYTICS_QUERY_INVALID",
  "ANALYTICS_FIELD_UNKNOWN",
  "ANALYTICS_FIELD_CAPABILITY_DENIED",
  "ANALYTICS_FILTER_INVALID",
  "ANALYTICS_AGGREGATION_INVALID",
  "ANALYTICS_QUERY_BUDGET_EXCEEDED",
  "ANALYTICS_QUERY_TIMEOUT",
  "ANALYTICS_RESULT_INVALID",
  "ANALYTICS_RESULT_TOO_LARGE",
  "ANALYTICS_VISUALIZATION_INVALID",
  "ANALYTICS_VIEW_INVALID",
  "ANALYTICS_VIEW_NOT_FOUND",
  "ANALYTICS_VIEW_REVISION_CONFLICT",
  "ANALYTICS_VIEW_NAME_CONFLICT",
  "ANALYTICS_QUERY_RUN_NOT_FOUND",
  "ANALYTICS_QUERY_RUN_NOT_READY",
  "ANALYTICS_QUERY_RUN_INVALID",
  "ANALYTICS_QUERY_RUN_UNAVAILABLE",
  "ANALYTICS_QUERY_RUN_IDEMPOTENCY_CONFLICT",
  "ANALYTICS_ARTIFACT_NOT_FOUND",
  "ANALYTICS_ARTIFACT_NOT_READY",
  "ANALYTICS_ARTIFACT_INVALID",
  "ANALYTICS_ARTIFACT_UNAVAILABLE",
  "ANALYTICS_ADAPTER_UNAVAILABLE",
] as const;

export const AnalyticsErrorCodeSchema = z.enum(ANALYTICS_ERROR_CODES);
export type AnalyticsErrorCode = z.infer<typeof AnalyticsErrorCodeSchema>;
